# Generated by Django 2.1.4 on 2019-10-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_auto_20191013_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
